#include "cc1101.h"

/* prefix system
    message from WUCAM (translated to text) : prefix '1', '2' or '3'
    echo of message from Serial (Java or monitor) : prefix '='
    message generated by Arduino : prefix '>'
 */
// litte endian utilities (work for unsigned int as well)
void to_16le( unsigned char * buf, int x ) {
  buf[0] = x;
  buf[1] = x >> 8;
  }

void to_32le( unsigned char * buf, long x ) {
  buf[0] = x;
  buf[1] = x >> 8;
  buf[2] = x >> 16;
  buf[3] = x >> 24;
  }

int from_16le( byte * bbuf ) {
  return ( ( bbuf[0] & 0xff ) | ( bbuf[1] << 8 ) );
  }

unsigned long from_32le( byte * bbuf ) {
  unsigned long retval = bbuf[3];
  retval <<= 8; retval |= bbuf[2];
  retval <<= 8; retval |= bbuf[1];
  retval <<= 8; retval |= bbuf[0];
  return retval; 
  }

// calcul CRC32 AIXM
unsigned long crc_aixm( const unsigned char *buf, byte leng )
{
unsigned long crc = 0;
byte i, j;
byte lebyte, topreg;
for ( j = 0; j < leng; j++ ) 
    {
    lebyte = buf[j];
    for ( i = 0; i < 8; i++ )
        {
        // topreg = ((unsigned char *)&crc)[3];  // very bad idea
        topreg = crc >> 24;  // high byte
        crc <<= 1;
        if  ( ( lebyte ^ topreg ) & 0x80 )  // test the MSB of each
            crc ^= 0x814141ABL;
        lebyte <<= 1;
        }
    }
return crc;
}

// verification de CRC32 dans packet p (le crc est a p + (p[0]-3))
// retour 1 si ok
int CRC32ok( byte * p )
{
byte len = p[0];
unsigned long local_crc = crc_aixm( p + 1, len - 4 );
unsigned long rx_crc = from_32le( p + (len-3) );
if  ( local_crc != rx_crc )
  {
  snprintf( CC.tbuf, sizeof(CC.tbuf), ">BAD rx CRC %08lx vs %08lx\n", local_crc, rx_crc );
  Serial.println( CC.tbuf );
  return 0;
  }
snprintf( CC.tbuf, sizeof(CC.tbuf), ">GOOD rx CRC %08lx\n", rx_crc );
Serial.println( CC.tbuf );
return 1;
}

// append a crc to a packet (with p[0]=len already including 4 crc bytes)
void appendCRC( unsigned char * p ) {
  byte len = p[0];
  unsigned long local_crc = crc_aixm( p + 1, len - 4 );
  snprintf( CC.tbuf, sizeof(CC.tbuf), ">tx CRC %08lx", local_crc );
  Serial.println( CC.tbuf );
  to_32le( p + len - 3, local_crc );
}

void setup() {
  Serial.begin(38400);
  int r = CC.GFSK_radio_init();
  if  ( r == 0 )
      Serial.println(">Radio init done");
  else Serial.println(">Radio init error");
}

byte default_plan[] = {148,152,24,49,210,8,167,94,198,210,214,84,227,195,128,0};

#define CRC
void interpreter( char buf[], byte buflen ) // zero-terminated string
{
Serial.print('='); Serial.println( buf );
if  (  buf[0] == '?' ) {  	// type '?' for dumps
    CC.dump_config();
    CC.dump_patable();
    return;
    }
byte flight;
switch ( buf[0] )   // prefix
      {
      case '1': flight = 101;   // send to wucam 101
        break; 
      case '2': flight = 102;   // send to wucam 102
        break; 
      case '3': flight = 103;   // send to wucam 103
        break;
      default: return;
      } 
  byte pack[61];
  pack[1] = flight;
  switch ( buf[1] ) {   // opcode letter { ndta cwlr PRZKN }
      // --- pilot orders NEWFP=0x70, DIRECT=0x4A, TURN=0x5E, NEWFL=0x14,
      case 'n': {
        pack[2] = 0x70;              // NEWFP
        byte i = 3; 
        for ( int j = 0; j < sizeof(default_plan); j++ )
            pack[i++] = default_plan[j];
        // here, LEN would be i - 1
        pack[0] = i + 3;  // add 4 for CRC, so LEN - i + 3
        appendCRC( pack );  
        } break;
      // space after single letter command is accepted but not mandatory  
      case 'd':
        pack[2] = 0x4A; pack[0] = 7;  // DIRECT
        if ( buf[2] == ' ' )
           pack[3] = atoi(buf+3); // 1 space skipped
        else pack[3] = atoi(buf+2); // no space, ok
        appendCRC( pack );  
        break; 
      case 't':
        pack[2] = 0x5E; pack[0] = 8;  // TURN
        if ( buf[2] == ' ' )
           to_16le( pack + 3, atoi(buf+3) );
        else to_16le( pack + 3, atoi(buf+2) );
        appendCRC( pack );  
        break; 
      case 'a':
        pack[2] = 0x14; pack[0] = 8;  // NEWFL
        if ( buf[2] == ' ' )
           to_16le( pack + 3, atoi(buf+3) );
        else to_16le( pack + 3, atoi(buf+2) );
        appendCRC( pack );  
        break;
      // --- pilot info requests REPFP=0x72, REPWCO=0x76, REPALT=0x16, REPRAT=0x7A
      case 'c' : pack[2] = 0x71; pack[0] = 2; // REQFP
        break;
      case 'w' : pack[2] = 0x75; pack[0] = 3; // REQWCO
        if ( buf[2] == ' ' )
           pack[3] = atoi(buf+3);
        else pack[3] = atoi(buf+2);
        break;
      case 'l' : pack[2] = 0x15; pack[0] = 2; // REQALT
        break;
      case 'r' : pack[2] = 0x79; pack[0] = 2; // REQRAT
        break;
      // --- simulation commands PAUSE=0x81, RESUME=0x82, RATECK=0x83, SRESET=0x84, SNEWFP=0x85
      case 'P': pack[2] = 0x81; pack[0] = 2;  // PAUSE
        break; 
      case 'R': pack[2] = 0x82; pack[0] = 2;  // RESUME
        break; 
      case 'K': pack[2] = 0x83; pack[0] = 3;  // RATECK
        if ( buf[2] == ' ' )
           pack[3] = atoi(buf+3);
        else pack[3] = atoi(buf+2);
        break; 
      case 'Z': pack[2] = 0x84; pack[0] = 2;  // SRESET
        break;
      case 'N': {                             // SNEWFP
        pack[2] = 0x85;
        byte i = 3; 
        for ( int j = 0; j < sizeof(default_plan); j++ )
            pack[i++] = default_plan[j];
        // here, LEN would be i - 1
        pack[0] = i + 3;  // add 4 for CRC, so LEN - i + 3
        appendCRC( pack );  
        } break;
      default: return;
      } // switch
  int resu = CC.tx_if_can( pack );
  if ( resu ) Serial.println(">tx error");
  else Serial.println(">tx ok"); 
  }


void handle_rx()
{
byte * pack = CC.extract_rx();
if ( ( pack[1] | 3 ) == (100|0x83) )  // accepte flights 100 a 103
  {
  char prefix = '0' + ( pack[1] & 3 );  // messages to Serial will have prefix 0, 1, 2 or 3
  switch  ( pack[2] )
    {
    case 0x42: { // VAAR : vector report
        int x, y, vx, vy;
        unsigned int fl, t;
        x = from_16le( pack + 3 );
        y = from_16le( pack + 5 );
        vx = from_16le( pack + 7 );
        vy = from_16le( pack + 9 );
        fl = (unsigned int)from_16le( pack + 11 );
        t = (unsigned int)from_16le( pack + 13 );
        snprintf( CC.tbuf, sizeof(CC.tbuf), "%c@ %d %d %d %d %u %u", prefix, x, y, vx, vy, fl, t );
        Serial.println( CC.tbuf );
    } break;
    case 0x00: { // WILCO
        unsigned long crc = from_32le( pack + 3 );
        snprintf( CC.tbuf, sizeof(CC.tbuf), "%cW %08lx", prefix, crc );
        Serial.println( CC.tbuf );
    } break;
    case 0x01: { // UNABLE
        unsigned long crc = from_32le( pack + 4 );
        snprintf( CC.tbuf, sizeof(CC.tbuf), "%cU %02x %08lx", prefix, pack[3], crc );
        Serial.println( CC.tbuf );
    } break;
    case 0x72: { // REPFP
        if  ( CRC32ok( pack ) )
            {
            byte j = 3;
            Serial.print( prefix ); Serial.print("c { ");
            while ( j < ( pack[0] - 3 ) )
                  { Serial.print(pack[j++]); Serial.print(' '); }
            Serial.println('}'); 
            }
    } break;
    case 0x76: { // REPWCO
        if  ( CRC32ok( pack ) )
            {
            byte j = 3;
            Serial.print( prefix ); Serial.print("w ");
            Serial.print(pack[j++]); Serial.print(" (");
            int x, y;
            while ( j < ( pack[0] - 3 ) )
                  {
                  x = from_16le( pack + j ); j += 2;
                  y = from_16le( pack + j ); j += 2;
                  snprintf( CC.tbuf, sizeof(CC.tbuf), "%d:%d ", x, y );
                  Serial.print( CC.tbuf );
                  }
            Serial.println(')'); 
            }
    } break;
    case 0x16: { // REPALT
        if  ( CRC32ok( pack ) )
            {
            byte j = 3;
            int x = from_16le( pack + j ); j += 2;
            int y = from_16le( pack + j ); j += 2;
            snprintf( CC.tbuf, sizeof(CC.tbuf), "%cl FLMIN %d FLMAX %d ", prefix, x, y );
            Serial.println( CC.tbuf );
            }
    } break;
    case 0x7A: { // REPRAT
        if  ( CRC32ok( pack ) )
            {
            byte j = 3;
            int x = from_16le( pack + j ); j += 2;
            int y = from_16le( pack + j ); j += 2;
            snprintf( CC.tbuf, sizeof(CC.tbuf), "%cr +%d ft/mn, -%d ft/mn, bank %d deg", prefix, x, y, pack[j] );
            Serial.println( CC.tbuf );
            }
    } break;
    default:
        CC.format_rx_to_Serial( pack );
    }
	}
else	CC.format_rx_to_Serial( pack );
}

void loop() {
static byte oldGDO0 = 0;
static char buf[116];
static int j = 0; // state of the machine !!
int c = Serial.read();
if  ( c != -1 )
    {
      if  ( ( c == 10 ) || ( j >= 15 ) )    // terminator
          {
          buf[j] = 0;   // usual terminator for a C string
          if  ( j ) interpreter( buf, j );
          j = 0;  // get ready for next message
          }
      else {
          buf[j] = c;
          j += 1;
      }
    }
if  ( ( digitalRead(2) ) && ( oldGDO0 == 0 ) ) {
    // delay(2);
    handle_rx();
    oldGDO0 = 1;
    }
else oldGDO0 = 0;
}
